databases:
  - name: lms
    plan: free
    databaseName: lms
    user: joy

services:
  - type: web
    plan: free
    name: website
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn website.asgi:application -k uvicorn.workers.UvicornWorker"    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4